#!/bin/bash

# Environment Setup Script for AudiScope
# This script helps you create the required environment files locally

set -e

echo "🔧 AudiScope Environment Setup"
echo "================================"
echo ""

# Check if any env files already exist
FILES_EXIST=false
if [ -f ".env.dev-cloud" ] || [ -f ".env.development" ] || [ -f ".env.staging" ]; then
    FILES_EXIST=true
fi

if [ "$FILES_EXIST" = true ]; then
    echo "⚠️  Warning: One or more environment files already exist."
    echo ""
    echo "Existing files:"
    [ -f ".env.dev-cloud" ] && echo "  - .env.dev-cloud"
    [ -f ".env.development" ] && echo "  - .env.development"
    [ -f ".env.staging" ] && echo "  - .env.staging"
    echo ""
    read -p "Do you want to overwrite them? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Existing files preserved."
        exit 0
    fi
fi

echo ""
echo "📝 Please provide the following values:"
echo "(Press Enter to use default values shown in brackets)"
echo ""

# AWS Cognito
read -p "AWS Region [eu-west-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-eu-west-1}

read -p "Cognito User Pool ID [eu-west-1_90PVu1scA]: " USER_POOL_ID
USER_POOL_ID=${USER_POOL_ID:-eu-west-1_90PVu1scA}

read -p "Cognito Client ID [4o01ocufgcskol74rr8cim7afq]: " CLIENT_ID
CLIENT_ID=${CLIENT_ID:-4o01ocufgcskol74rr8cim7afq}

# API Gateway
read -p "API Gateway URL [https://m0coihjhbk.execute-api.eu-west-1.amazonaws.com]: " API_GATEWAY_URL
API_GATEWAY_URL=${API_GATEWAY_URL:-https://m0coihjhbk.execute-api.eu-west-1.amazonaws.com}

# Dev Cloud API
read -p "Dev Cloud Core API URL [http://core-api-dev-alb-766481977.eu-west-1.elb.amazonaws.com]: " DEV_CORE_API
DEV_CORE_API=${DEV_CORE_API:-http://core-api-dev-alb-766481977.eu-west-1.elb.amazonaws.com}

# Knowledge Base
read -p "Knowledge Base ID [5WDOTFQ8QC]: " KB_ID
KB_ID=${KB_ID:-5WDOTFQ8QC}

# Optional: Staging API
read -p "Staging Core API URL (optional): " STAGING_API
STAGING_API=${STAGING_API:-https://your-staging-api.example.com}

echo ""
echo "✨ Creating environment files..."
echo ""

# Create .env.dev-cloud
cat > .env.dev-cloud << EOF
# Development Environment - All Cloud Resources
# Auto-generated by setup-env.sh

# AWS Cognito
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}

# AWS API Gateway (Audio Assessment Pipeline)
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Product Management - Cloud Development)
NEXT_PUBLIC_API_URL=${DEV_CORE_API}
NEXT_PUBLIC_CORE_API_URL=${DEV_CORE_API}/api

# AWS Bedrock Knowledge Base
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# Sentry (disabled for development)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.dev-cloud"

# Create .env.development
cat > .env.development << EOF
# Development Environment - LocalStack + Local Backend
# Auto-generated by setup-env.sh

# AWS Cognito (Real AWS)
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}

# AWS API Gateway (Real AWS)
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Local Development)
NEXT_PUBLIC_API_URL=http://localhost:5002
NEXT_PUBLIC_CORE_API_URL=http://localhost:5002/api

# AWS Bedrock Knowledge Base (Real AWS)
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# LocalStack S3 Override
NEXT_PUBLIC_S3_ENDPOINT_OVERRIDE=http://localhost:4566

# Sentry (disabled for development)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.development"

# Create .env.staging
cat > .env.staging << EOF
# Staging Environment
# Auto-generated by setup-env.sh

# AWS Cognito
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}

# AWS API Gateway
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Staging)
NEXT_PUBLIC_API_URL=${STAGING_API}
NEXT_PUBLIC_CORE_API_URL=${STAGING_API}/api

# AWS Bedrock Knowledge Base
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# Sentry (optional for staging)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.staging"

echo ""
echo "🎉 Environment setup complete!"
echo ""
echo "Next steps:"
echo "1. Run 'pnpm install' if you haven't already"
echo "2. Start development:"
echo "   - pnpm dev     (cloud resources)"
echo "   - pnpm local   (LocalStack + local backend)"
echo "   - pnpm staging (staging environment)"
echo ""
echo "⚠️  Security Note:"
echo "These files are gitignored and will NOT be committed."
echo "Keep your credentials secure!"
echo ""
