#!/bin/bash

# Environment Setup Script for AudiScope
# This script helps you create the required environment files locally

set -e

echo "🔧 AudiScope Environment Setup"
echo "================================"
echo ""

# Check if any env files already exist
FILES_EXIST=false
if [ -f ".env.dev-cloud" ] || [ -f ".env.development" ]; then
    FILES_EXIST=true
fi

if [ "$FILES_EXIST" = true ]; then
    echo "⚠️  Warning: One or more environment files already exist."
    echo ""
    echo "Existing files:"
    [ -f ".env.dev-cloud" ] && echo "  - .env.dev-cloud"
    [ -f ".env.development" ] && echo "  - .env.development"
    echo ""
    read -p "Do you want to overwrite them? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Existing files preserved."
        exit 0
    fi
fi

echo ""
echo "📝 Please provide the following values:"
echo "(Press Enter to use default values shown in brackets)"
echo ""

# Keycloak
read -p "Keycloak URL [http://localhost:8080]: " KEYCLOAK_URL
KEYCLOAK_URL=${KEYCLOAK_URL:-http://localhost:8080}

read -p "Keycloak Realm [audiscope]: " KEYCLOAK_REALM
KEYCLOAK_REALM=${KEYCLOAK_REALM:-audiscope}

read -p "Keycloak Client ID [audiscope-web]: " KEYCLOAK_CLIENT_ID
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-audiscope-web}

read -p "Keycloak Client Secret: " KEYCLOAK_CLIENT_SECRET
if [ -z "$KEYCLOAK_CLIENT_SECRET" ]; then
    echo "⚠️  Warning: No Keycloak client secret provided. You'll need to add it manually."
    KEYCLOAK_CLIENT_SECRET="your-client-secret-here"
fi

# NextAuth
read -p "NextAuth Secret (leave blank to generate): " NEXTAUTH_SECRET
if [ -z "$NEXTAUTH_SECRET" ]; then
    echo "Generating NextAuth secret..."
    NEXTAUTH_SECRET=$(openssl rand -base64 32)
fi

# API Gateway
read -p "API Gateway URL [https://m0coihjhbk.execute-api.eu-west-1.amazonaws.com]: " API_GATEWAY_URL
API_GATEWAY_URL=${API_GATEWAY_URL:-https://m0coihjhbk.execute-api.eu-west-1.amazonaws.com}

# Dev Cloud API
read -p "Dev Cloud Core API URL [http://core-api-dev-alb-766481977.eu-west-1.elb.amazonaws.com/api]: " DEV_CORE_API
DEV_CORE_API=${DEV_CORE_API:-http://core-api-dev-alb-766481977.eu-west-1.elb.amazonaws.com/api}

# Knowledge Base
read -p "Knowledge Base ID [5WDOTFQ8QC]: " KB_ID
KB_ID=${KB_ID:-5WDOTFQ8QC}

echo ""
echo "✨ Creating environment files..."
echo ""

# Create .env.dev-cloud
cat > .env.dev-cloud << EOF
# Development Environment - All Cloud Resources
# This file is NOT committed to git for security

# Multi-Tenant Configuration
# Development: Default tenant for localhost (audiscope is the fallback tenant)
DEV_TENANT=audiscope

# Keycloak Authentication (Server-side - NOT exposed to browser)
KEYCLOAK_ISSUER=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}

# NextAuth Configuration
NEXTAUTH_URL=http://audiscope.localhost:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Keycloak Public Configuration (Client-side - exposed to browser)
NEXT_PUBLIC_KEYCLOAK_URL=${KEYCLOAK_URL}
NEXT_PUBLIC_KEYCLOAK_REALM=${KEYCLOAK_REALM}
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}

# AWS API Gateway (Audio Assessment Pipeline)
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Product Management - Cloud Development)
# Server-side only - used in next.config.mjs for API rewrites (/api/core/*)
CORE_API_URL=${DEV_CORE_API}

# AWS Bedrock Knowledge Base
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# Sentry (disabled for development)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.dev-cloud"

# Create .env.development
cat > .env.development << EOF
# Development Environment - LocalStack + Local Backend
# Auto-generated by setup-env.sh

# AWS Cognito (Real AWS)
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}

# AWS API Gateway (Real AWS)
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Local Development)
NEXT_PUBLIC_API_URL=http://localhost:5002
NEXT_PUBLIC_CORE_API_URL=http://localhost:5002/api

# AWS Bedrock Knowledge Base (Real AWS)
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# LocalStack S3 Override
NEXT_PUBLIC_S3_ENDPOINT_OVERRIDE=http://localhost:4566

# Sentry (disabled for development)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.development"

# Create .env.staging
cat > .env.staging << EOF
# Staging Environment
# Auto-generated by setup-env.sh

# AWS Cognito
NEXT_PUBLIC_AWS_REGION=${AWS_REGION}
NEXT_PUBLIC_USER_POOL_ID=${USER_POOL_ID}
NEXT_PUBLIC_USER_POOL_CLIENT_ID=${CLIENT_ID}

# AWS API Gateway
NEXT_PUBLIC_API_GATEWAY_URL=${API_GATEWAY_URL}

# Core API (Staging)
NEXT_PUBLIC_API_URL=${STAGING_API}
NEXT_PUBLIC_CORE_API_URL=${STAGING_API}/api

# AWS Bedrock Knowledge Base
NEXT_PUBLIC_KNOWLEDGE_BASE_ID=${KB_ID}

# Sentry (optional for staging)
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

echo "✅ Created .env.staging"

echo ""
echo "🎉 Environment setup complete!"
echo ""
echo "Next steps:"
echo "1. Run 'pnpm install' if you haven't already"
echo "2. Start development:"
echo "   - pnpm dev     (cloud resources)"
echo "   - pnpm local   (LocalStack + local backend)"
echo "   - pnpm staging (staging environment)"
echo ""
echo "⚠️  Security Note:"
echo "These files are gitignored and will NOT be committed."
echo "Keep your credentials secure!"
echo ""
